# Generated by Django 5.2.6 on 2026-09-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['-timestamp', '-id'], 'verbose_name': 'Tracking Event', 'verbose_name_plural': 'Tracking Events'},
        ),
    ]
