# Generated by Django 5.2.6 on 2026-09-21 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trackingevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
